// Charities
export const CHARITIES_REQUEST = 'CHARITIES_REQUEST';
export const CHARITIES_SUCCESS = 'CHARITIES_SUCCESS';
export const CHARITIES_FAILURE = 'CHARITIES_FAILURE';

// Donations
export const DONATIONS_REQUEST = 'DONATIONS_REQUEST';
export const DONATIONS_SUCCESS = 'DONATIONS_SUCCESS';
export const DONATIONS_FAILURE = 'DONATIONS_FAILURE';
